### ISSUE TITLE
MVP Form based editor

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#208]
## Description of new feature

Have a page where it is possible to write in separate rows things like:

*A* *phosphorylates* *B* at *C*

With "write" I mean that A, B are input fields that possibly autocomplete/ground entities, phosphorylates is called from a list of different activation mechanisms (interacts/phosphorylates/..?), and C is probably (in this case at least) a number starting from 1.

Nice to have: A, B could use the wizard that is applied to the nodes in the Cytoscape editor

## Motivation for new feature

A different editing mechanism for documents

**Comment by jvwong** [comment]
For your consideration, the [REACH results explorer](http://agathon.sista.arizona.edu:8080/rexplorer/):

![reach_results_explorer](https://user-images.githubusercontent.com/4706307/37226679-c05076ae-23a8-11e8-9a3b-9427ab9a56af.gif)

**Comment by sacdallago** [comment]
To make people happy, how about emulating this for starters?

One quick improvement over this could be that _ATM_ and _TP53_ will have the wizard as the nodes in Cytoscape have.

**Comment by sacdallago** [comment]
From notes on 03.17:

Should allow defining interactions, phosphorylation, and enzyme reaction.

![image](https://user-images.githubusercontent.com/6240943/37601042-732b8120-2b5f-11e8-845c-7eb2af5bda71.png)


In terms of UI, the "Form editor" is probably not a good title. Something more biologist who doesn't care about CS could be a good idea, like "Insert pathway information in text".

But in general, it was well received!

**Comment by d2fong** [comment]
## TODO:
- [ ] find out how to visually represent the wizard stepper so that users don't think it is autocomplete.  I think it is harder to show a wizard for each entity in a form because they will think it is autocomplete.  I think it is easier for users to not think think the wizard is autocomplete in the graph editor because it doesn't look like a form.
- [ ] find out how to use the wizard stepper for each form entry
- [ ] find out how to convert the dummy model to a factoid model

**Comment by d2fong** [comment]
Basic form interface implemented.  Discussion for what constitutes MVP is in #225
