### ISSUE TITLE
Determine what should go in the form MVP

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#225]
A basic form interface for Factoid exists where users can choose an interaction type and type in entity names

Determine what should go in the form MVP

- should we have a fully fleshed out wizard like form or is just text enough?

Will post over flow of ideas from #208

**Comment by d2fong** [comment]
## Interactions
What interactions should this form support and how should they be represented visually

Current form interface has a drop down that users can choose from: 'enzyme interaction', 'phosphorylation', 'other', 'interacts with'.

**Comment by d2fong** [comment]
## Form Wizard

The graph editor has a wizard tooltip for each node on click.  It might not make sense to use this for the form because users might think it is a autocomplete and then ignore it entirely.

## TODO
- [ ] find out if we need the entities in the **form MVP** to be grounded
- [ ] find out if we need the entities  in the **form MVP** to have an associated organism
- [ ] find out if we need the entities  in the **form MVP** to have an associated modification

If we don't need any of these we can just keep the text box for entity names.  If we need organism/modification capability, we can just add another field for each entity.  If we need grounding we need to really think about how the design of this form will look like.
