### ISSUE TITLE
Send 520 when REACH output cannot be converted to a Factoid model

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#229]
Continuation of  #207 with a reduced scope

## Description of new feature

Reach 

### TODO
- [ ] Determine the conditions and cases where REACH's response cannot be converted into a factoid model
- [ ] Determine the business logic related to processing REACH output
- [ ] When it is determined that this REACH response can't be converted to a model, send a 520 error in the response

 (4) NLP returns a response that can't be converted to factoid model (520)
Log to the server (the inputted text + the fact that the result can't be serialized)
Tell the user that "there was a problem with processing your text" and suggest to either change text or start on an empty document
business logic related to processing reach output -- sometimes there are errors produced (not well defined).

## Motivation for new feature

The hypothesis is that providing users with reasons why NLP failed will allow them to cope with why the app failed to process their paper.  By suggesting alternatives such as starting with an empty document, users will have a better understanding of what to do.

**Comment by d2fong** [comment]
Notes
- Difficult to detect cases it will fail
- Difficult to solve this problem entirely
- It should be considered that the basic error message we have right now is enough

**Comment by sacdallago** [comment]
Good. As discussed in various places and here: let's first collect some statistics and then try working out cases from there. If the error rate is very low and/or doesn't disrupt the flow significantly (e.g.: users can still create networks and morale is not particularly altered) then we can even just accept it, since, as you noted:
> Difficult to solve this problem entirely
