### ISSUE TITLE
v0.1 - known shortcomings

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#319]
High priority:

- [x] From+Graph: when creating entities in form, they don't layout well in graph. Fix is on the way #311
- [ ] Form+Graph+NLP: Get a list of papers to test against and use these to improve form+graph

Medium priority:

- [x] From: Creation of new entries should be unified (instead of the hard classification as is now) --> single button. Fix on the way #311 
- [x] Form: Branding on the form 
- [x]  From: Can not represent general interaction (but can do so in graph editor).  See also  #297
- [x] From: task list (checks over or beside entity boxes) needs to be integrated.

Low priority:

- [x] From: UX improvements on interaction creation (parallelize promise execution) [code speedup]
- [x] From: focus on text input when creating a new interaction or selecting an ungrounded entity
- [ ] From: No links to current document -- Next sprint #337

**Comment by metincansiper** [comment]
> From: Can not represent general interaction (but can do so in graph editor).

I tried possible combinations on this.

- I created ``chemical interacts with protein`` and ``chemical interacts with chemical`` from form editor and the interactions were available as expected in the network editor. 
- I did the same thing from the network editor and interactions were successfully listed under molecular interaction in form editor. 

Is the problem about ``general`` interaction type or ``protein and chemical`` interaction type? I suppose protein and chemical is the one that is not supported by the form editor.

**Comment by sacdallago** [comment]
From https://github.com/PathwayCommons/factoid/issues/221#issuecomment-398861630 :

- [ ] My factoids makes use of user's localstorage. This might need be extended with user auth stuff on the server side, but most likely this is heavily influenced by later collaborations w/ editors

**Comment by maxkfranz** [comment]
> My factoids makes use of user's localstorage. 

I don't think that's something that should be changed at this point.

**Comment by sacdallago** [comment]
@maxkfranz not changed, no. But made aware of.

**Comment by sacdallago** [comment]
- [ ] NLP highlight is buggy https://github.com/PathwayCommons/factoid/issues/333

**Comment by maxkfranz** [comment]
Remaining issues put into Sprint 5: https://github.com/PathwayCommons/factoid/milestone/9

Leaving this issue open to discuss tagging/merging for 0.1 on Tue call

**Comment by maxkfranz** [comment]
Tag v0.1.0 -- the initial fixes and refactoring we did

Tag v0.2.0 -- the state at the last call

Closing
